### ISSUE TITLE
동시에 스터디 3개를 하는 박사가 있다?!

### ISSUE THREAD

**Issue by long8v** [jonghyunlee1993/SparkStudy#1]
해명하세요

**Comment by jonghyunlee1993** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

아닠ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021년 3월 31일 (수) 오후 4:47, long8v ***@***.***>님이 작성:

**Comment by jonghyunlee1993** [comment]
@long8v 이것은 수업 들으면서 하는 것에 불과합니다... 이슈 닫습니다... ㅎ

**Comment by long8v** [comment]
어우 맘대로 닫지마세요!!
